[package]
name = "bgapi"
version = "0.0.0"
authors = ["Arthur Crippa BÃºrigo <arthurcburigo@gmail.com>"]
license = "MIT"
description = "Libraty for creating and parsing BGAPI packets."

[dependencies]
bytes = "0.4"
num-traits = "0.2"
num-derive = "0.2"
